# Q1.

#### Include Dependencies

In [157]:
#Dependencies
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix

#### Load iris dataset

In [158]:
data = load_iris()
df = pd.DataFrame(data['data'], columns=data['feature_names'])
df['target'] = data['target']
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [159]:
df.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
145       2  
146       2  
147       2  
148       2  
149       2

#### Extract X as all columns except the last column and Y as last column

In [160]:
X = df.drop('target', axis=1).values
y = df['target'].values
#print(X.shape)
#print(y.shape)

#### Split dataset into test and train set

In [161]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 82)

#### Model building

In [162]:
# Feature Scaling to bring the variable in a single scale
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

nvclassifier = GaussianNB()
nvclassifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

#### Predict

In [164]:
y_pred = nvclassifier.predict(X_test)
#print(y_pred)
#y_compare = np.vstack((y_test,y_pred)).T
#y_compare[:5,:]

#### Confusion matrix

In [165]:
#cm = confusion_matrix(y_test, y_pred)
#print(cm)
pd.crosstab(y_test, y_pred, rownames=['True'], colnames=['Predicted'], margins=True)

Predicted   0   1   2  All
True                      
0          18   0   0   18
1           0  10   1   11
2           0   2  14   16
All        18  12  15   45

#### Accuracy

In [166]:
a = cm.shape
corrPred = 0
falsePred = 0

for row in range(a[0]):
    for c in range(a[1]):
        if row == c:
            corrPred +=cm[row,c]
        else:
            falsePred += cm[row,c]
print('Correct predictions: ', corrPred)
print('False predictions', falsePred)
print ('\n\nAccuracy of the Naive Bayes Clasification is: ', corrPred/(cm.sum()))

Correct predictions:  42
False predictions 3


Accuracy of the Naive Bayes Clasification is:  0.9333333333333333


#### Classification Report

In [167]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       0.83      0.91      0.87        11
           2       0.93      0.88      0.90        16

    accuracy                           0.93        45
   macro avg       0.92      0.93      0.92        45
weighted avg       0.94      0.93      0.93        45



# Q2

#### Import dependencies

In [368]:
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn import model_selection
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

#### Load dataset

Download car.data in the same directory this notebook is in. The column names are from names file and modified a bit for better understanding. 

In [369]:
cardf = pd.read_csv('car.data', names=['buy_price', 'maintenance', 'num_doors', 'persons', 'trunk_size', 'safety','target_class'])

In [370]:
cardf.head()

buy_price maintenance num_doors persons trunk_size safety target_class
0     vhigh       vhigh         2       2      small    low        unacc
1     vhigh       vhigh         2       2      small    med        unacc
2     vhigh       vhigh         2       2      small   high        unacc
3     vhigh       vhigh         2       2        med    low        unacc
4     vhigh       vhigh         2       2        med    med        unacc

In [371]:
cardf.tail()

buy_price maintenance num_doors persons trunk_size safety target_class
1723       low         low     5more    more        med    med         good
1724       low         low     5more    more        med   high        vgood
1725       low         low     5more    more        big    low        unacc
1726       low         low     5more    more        big    med         good
1727       low         low     5more    more        big   high        vgood

In [372]:
cardf.describe()

buy_price maintenance num_doors persons trunk_size safety target_class
count       1728        1728      1728    1728       1728   1728         1728
unique         4           4         4       3          3      3            4
top        vhigh       vhigh     5more    more      small    med        unacc
freq         432         432       432     576        576    576         1210

#### Data transformation and encoding

In [373]:
cardf.target_class.unique()

array(['unacc', 'acc', 'vgood', 'good'], dtype=object)

In [374]:
cardf.safety.unique()

array(['low', 'med', 'high'], dtype=object)

In [375]:
cardf['safety'] = cardf['safety'].map({'low': 0, 'med': 1, 'high': 2})

In [376]:
cardf.safety.unique()

array([0, 1, 2])

In [377]:
cardf.trunk_size.unique()

array(['small', 'med', 'big'], dtype=object)

In [378]:
cardf['trunk_size'] = cardf['trunk_size'].map({'small': 0, 'med': 1, 'big': 2})

In [379]:
cardf.trunk_size.unique()

array([0, 1, 2])

In [380]:
cardf.persons.unique()

array(['2', '4', 'more'], dtype=object)

In [381]:
cardf['persons'] = cardf['persons'].map({'2': 2, '4': 4, 'more': 5})

In [382]:
cardf.persons.unique()

array([2, 4, 5])

In [383]:
cardf.num_doors.unique()

array(['2', '3', '4', '5more'], dtype=object)

In [384]:
cardf['num_doors'] = cardf['num_doors'].map({'2': 2, '3': 3, '4': 4, '5more': 5})

In [385]:
cardf.num_doors.unique()

array([2, 3, 4, 5])

In [386]:
cardf.maintenance.unique()

array(['vhigh', 'high', 'med', 'low'], dtype=object)

In [387]:
cardf['maintenance'] = cardf['maintenance'].map({'vhigh':3, 'high':2, 'med':1, 'low':0})

In [388]:
cardf.maintenance.unique()

array([3, 2, 1, 0])

In [389]:
cardf.buy_price.unique()

array(['vhigh', 'high', 'med', 'low'], dtype=object)

In [390]:
cardf['buy_price'] = cardf['buy_price'].map({'vhigh':3, 'high':2, 'med':1, 'low':0})

In [391]:
cardf.buy_price.unique()

array([3, 2, 1, 0])

#### Extract X as all columns except the last column and Y as last column

In [392]:
X = cardf.drop('target_class', axis=1).values
y = cardf['target_class'].values

#### Tunning the model parameter 

In [328]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import make_scorer
from sklearn.metrics import f1_score

In [329]:
c_values = list(np.arange(1,100))

In [350]:
param_grid = [
    {
        'C':c_values,
        'penalty': ['l1'],
        'solver':['liblinear'],
        'multi_class': ['ovr'],
        'random_state':[42],
        'max_iter' :[5000]
    },{
        'C':c_values,
        'penalty': ['l2'],
        'solver':['newton-cg','lbfgs'],
        'multi_class': ['multinomial'],
        'random_state':[42],
        'max_iter' :[5000]
    }
]

In [351]:
scorer = make_scorer(f1_score, average = 'weighted')

In [352]:
#CV cross-validation generator cv=10 for 10 fold cross-validation
grid = GridSearchCV(LogisticRegression(),param_grid, cv=10, scoring='accuracy')

In [353]:
grid.fit(X,y)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/model_selection/_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=10, error_score='raise-deprecating',
             estimator=LogisticRegression(C=1.0, class_weight=None, dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=100, multi_class='warn',
                                          n_jobs=None, penalty='l2',
                                          random_state=None, solver='warn',
                                          tol=0.0001, verbose=0,
                                          warm_start=False),
             iid='warn', n_jobs=None,
             param_grid=[{'C': [1, 2, 3, 4, 5, 6, 7...
                          'penalty': ['l1'], 'random_state': [42],
                          'solver': ['liblinear']},
                         {'C': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,
                                15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
         

In [354]:
print(grid.best_params_)
print('Best Score: {:.2f}%'.format(grid.best_score_*100))

{'C': 5, 'max_iter': 5000, 'multi_class': 'multinomial', 'penalty': 'l2', 'random_state': 42, 'solver': 'newton-cg'}
Best Score: 81.25%


#### Model Parameters

C: Inverse of regularization strength.Regularization is applying a penalty to increasing the magnitude of parameter values in order to reduce overfitting.
              
multi_class: If the option chosen is ‘ovr’, then a binary problem is fit for each label. For ‘multinomial’ the loss minimised is the multinomial loss fit across the entire probability distribution, even when the data is binary.
              
penalty: Used to specify the norm used in the penalization.The ‘newton-cg’solver support only l2 penalties.    
        
random_state: random_state is the seed used by the random number generator. 
    
solver: Algorithm to use in the optimization problem.Its a multiclass problems, hence ‘newton-cg’is used to handle multinomial loss 

#### Logistic Regression Model

In [355]:
logreg = LogisticRegression(C=7, multi_class='multinomial', penalty='l2', random_state=42, solver='newton-cg')
logreg.fit(X_train, y_train)
y_pred = logreg.predict(X_test)
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(logreg.score(X_test, y_test)))

Accuracy of logistic regression classifier on test set: 0.85


#### Confusion Matrix

In [356]:
#confusion_matrix = confusion_matrix(y_test, y_pred)
#print(confusion_matrix)
pd.crosstab(y_test, y_pred, rownames=['True'], colnames=['Predicted'], margins=True)

Predicted  acc  good  unacc  vgood  All
True                                   
acc         78     3     32      2  115
good        13    11      0      1   25
unacc       25     0    337      1  363
vgood        3     0      0     13   16
All        119    14    369     17  519

#### Accuracy

In [357]:
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(logreg.score(X_test, y_test)))

Accuracy of logistic regression classifier on test set: 0.85


In [358]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         acc       0.66      0.68      0.67       115
        good       0.79      0.44      0.56        25
       unacc       0.91      0.93      0.92       363
       vgood       0.76      0.81      0.79        16

    accuracy                           0.85       519
   macro avg       0.78      0.71      0.73       519
weighted avg       0.85      0.85      0.84       519

